sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: wgzy1212
  redis:
    host: localhost
    port: 6379
    database: 10
  wechat:
    appid: wx6b7e843766b46e4d
    secret: 310c515868ebedc8926c45f268a5e1ca